---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
      - name: starbucks
        image: sai49019/starbucks:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: starbucks
spec:
  type: LoadBalancer
  selector:
    app: starbucks
  ports:
  - port: 80
    targetPort: 3000


